version: 2.1

jobs:
  build:
    docker:
      - image: "debian:latest"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing build tools
          command: 'sudo apt-get update && apt-get install -y gcc-9 g++-9 wget pkg-config build-essential'
      - run:
          name: Install CppuTest
          command: 'bash scripts/install_cpputest.sh'
      - run:
          name: Dir setup
          command: 'mkdir build && mkdir build-release && mkdir build-asan'
      - run:
          name: Debug build
          command: 'cd build && cmake ../src -DCMAKE_BUILD_TYPE=Debug && make -j5'
      - run:
          name: Release build
          command: 'cd build && cmake ../src -DCMAKE_BUILD_TYPE=Release && make -j5'
      - run:
          name: Debug build
          command: 'cd build && cmake ../src -DCMAKE_BUILD_TYPE=Release -DWITH_ASAN=ON && make -j5'