version: 2.1

jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing Build tools
          command: 'apt-get update && apt-get install -y g++-9 cmake cpputest pkg-config'
      - run:
          name: Dir setup
          command: 'mkdir build && mkdir build-release && mkdir build-asan'
      - run:
          name: Debug build
          command: 'cd build && cmake ../src -DCMAKE_BUILD_TYPE=Debug'
      - run:
          name: Release build
          command: 'cd build && cmake ../src -DCMAKE_BUILD_TYPE=Release'
      - run:
          name: Debug build
          command: 'cd build && cmake ../src -DCMAKE_BUILD_TYPE=Release -DWITH_ASAN=ON'